# Use root/example as user/password credentials
version: '3.1'

services:
  mysql_database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: COREABLE
    ports:
      - '3306:3306'
    expose:
      - '3306'