service: coreable

provider: 
  name: aws
  runtime: nodejs10.x
  stage: production
  region: us-east-2

functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY {proxy+}
      - http: ANY /